### ISSUE TITLE
Wrong result on large dataset > 5K images

### ISSUE THREAD

**Issue by nupnik267** [elisemercury/Duplicate-Image-Finder#103]
I tried on 13K images but results are not coming correct, on <5K images it’s working great. So my issue is even though my similarity is set to 5(i.e default), search.result contain result with >5 mse i.e even 100,101,etc mse are appended to it, also whose mse is 0 is not the exact duplicate of each other. I think there is issue in mapping and result generation of images with >5K. 

Note: I am passing multiple directories as list.
![image](https://github.com/user-attachments/assets/8165d37f-ea4f-4ac3-9112-8c1de416afdc)
![image](https://github.com/user-attachments/assets/8d1270b0-af54-4249-83a2-34588fcc6424)

**Comment by elisemercury** [comment]
Hi @nupnik267,

Thanks for opening the issue!

There have been some improvements and bug fixes in the algorithm with version [`4.1.2`](https://github.com/elisemercury/Duplicate-Image-Finder/releases/tag/v4.1.2). May I ask you to test the new version on the same dataset and see whether the issues still persist?

Thanks,
Elise
