### ISSUE TITLE
CL interface

### ISSUE THREAD

**Issue by cyremur** [elisemercury/Duplicate-Image-Finder#11]
Would be lovely to be able to invoke this directly from command line.

**Comment by elisemercury** [comment]
Hi @cyremur!
Thank you very much for your input! A CLI interface would indeed be a great addition to the current functionality. This might be considered in the upcoming releases.
Again, thank you and all the best,
Elise

**Comment by elisemercury** [comment]
Hi @cyremur,
The usage of difPy via the CLI is now supported with version 2.4.
All the best,
Elise
