### ISSUE TITLE
Silent deletion and subfolder traversal

### ISSUE THREAD

**Issue by cyremur** [elisemercury/Duplicate-Image-Finder#12]
I'm planning to use this in a semi-automated situation and it would be nice to have the option to suppress the user confirmation for silent deletion.

Will lift some code for now and adapt for my use case. Thanks for this project!

Also, it could be interesting to add subfolder traversal.

**Comment by elisemercury** [comment]
Hi cyremur!

Thanks a lot for your input! The silent deletion feature has been added with the update of v2.2. The sub-folder traversal feature will be considered with future updates.

All the best,
Elise
