### ISSUE TITLE
Path handling improvements

### ISSUE THREAD

**Issue by tme-MetaSwitch** [elisemercury/Duplicate-Image-Finder#13]
Looking at the code, I see that paths are often joined using "+" and that path separators are assumed to be '/' are put in as literal text. I needed to put some workarounds in my calling code (on Windows 11) to handle this. It would be more portable and maintainable to use os.path.join() and other portable path handling functions.

Just a suggestion, not a request.

**Comment by elisemercury** [comment]
Hi tme-MetaSwitch

Thanks a lot for your input! This improvement has been considered with the new release v2.2.

All the best,
Elise
