### ISSUE TITLE
Ctrl-C doens't work

### ISSUE THREAD

**Issue by TheLastGimbus** [elisemercury/Duplicate-Image-Finder#32]
Hi! I launched my python script by accident and couldn't close it because Ctrl-C doesn't work while difPy is running :/

**Comment by elisemercury** [comment]
Hi @TheLastGimbus,
Thanks for your feedback! Indeed, this is an issue that I have also experienced myself and I am working on having this resolved with the next version of difPy!
Again, thanks so much for your feedback.
All the best,
Elise

**Comment by TheLastGimbus** [comment]
Hmm.. yeah...
I think giving it a path with the folder name included would be good 👍

**Comment by elisemercury** [comment]
Hi @TheLastGimbus,
I added manual handling of KeyboardInterrupt, and from my side the issue seems to have gotten better. Nevertheless, sometimes it still requires you to click CTRL-C multiple times so that the interruption it is catched. 
Again thanks and all the best,
Elise

**Comment by TheLastGimbus** [comment]
Whoa, thanks!
