### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by TheLastGimbus** [elisemercury/Duplicate-Image-Finder#34]
Hi!
I have nice AMD cpu with 8 cores. And when I'm searching thorough 2 big folders, it takes a lof of time because only one of them is being use

Dividing the work into multiple threads seems as obvious task in this library - would be awesome if you implemented it! (or suggested how it could be done for someone to pull request)

**Comment by elisemercury** [comment]
Hi @TheLastGimbus,
Thanks a lot for your feedback! I will definitely look into your idea. In the meantime, if you want to implement this feature yourself, feel free to open a pull request to this repo.
Thanks and all the best,
Elise

**Comment by elisemercury** [comment]
Hi @TheLastGimbus, 

I'm happy to let you know that difPy v4 now comes with multiprocessing. Thanks for your suggestion!

All the best,
Elise

**Comment by TheLastGimbus** [comment]
I'm always happy to get a notifiaction about new stuff here! Great job!
