### ISSUE TITLE
Sort files by date/name/etc

### ISSUE THREAD

**Issue by ppizarror** [elisemercury/Duplicate-Image-Finder#4]
Hi! Thanks for your library, super useful.

I have a suggestion regarding the ordering of the files previous to checking. Having a way to manipulate the order of the files to be checked would be a nice addition for me, as I'm adding new files and I'd like to want to know if these recent new files are repeated, rather than the names they have.

For instance 4 different ordering mechanisms could be added:

dif.ORDER_BY_NAME_DESC # default
dif.ORDER_BY_NAME_ASC # ascendant names
dif.ORDER_BY_DATE_DESC
dif.ORDER_BY_DATE_ASC

by default, compare_images can have a param like order=dif.ORDER_BY_NAME_DESC. And can be updated by the user.
Do you like that behavior?

Greetings! :)

**Comment by elisemercury** [comment]
Hello ppizarror,
In the new version difPy v2.0 the feature has been added for sorting the output filenames alphabetically. The other ordering methods you listed might be considered for future updates.
Thanks a lot for your input!
