### ISSUE TITLE
Same duplicate in different keys

### ISSUE THREAD

**Issue by Fenho** [elisemercury/Duplicate-Image-Finder#42]
We have found that when you use `dif` within a folder of folders, there may be some unexpected behaviour. In our case, we have a pair of duplicates in one folder, and a third duplicate in another one. This makes it so result will output:

![image](https://user-images.githubusercontent.com/32397663/197809132-35ae0cce-80b1-4ea2-b3cd-ba869f9b79bd.png)

So an element that was detected as duplicate is being used later as a key. We do not know if this is bug or a feature, but it may be inconsistent with the behavior of not repeating duplicates in later keys. Still, for our use we can just use a set() as a workaround to ignore "duplicates of duplicates".

Nice work on the tool, it has helped us a lot with a nasty database. Thank you, have a nice day!

![5m0RZ](https://user-images.githubusercontent.com/32397663/197811120-14605234-33d5-4e8e-801d-c47e2a78922f.jpg)

**Comment by elisemercury** [comment]
Hi @Fenho,
Thanks for noticing the issue and opening an issue! This indeed is not supposed to be a feature and produces quite a bit of confusion in the output. I'll work on a fix in the new version of difPy. 
Thanks and all the best,
Elise

**Comment by elisemercury** [comment]
Hi @Fenho,
The issue you raised has now been fixed with version 2.4.5. Again, thanks a lot for your contribution!
All the best,
Elise

**Comment by Fenho** [comment]
Great! Thank you for addressing it 😁
