### ISSUE TITLE
run the CLI, how?

### ISSUE THREAD

**Issue by GerritKuilder** [elisemercury/Duplicate-Image-Finder#49]
Hello, 

call me stupid but I try to run the cli version of this code, I can run it from a basic script:
from difPy import dif
search = dif("C:/Path/to/Folder/")

and this works.
but  if I run it as python dif.py -A "C:/Path/to/Folder_A/"

I get a no such file or directory

And yes, not very familiar with python (yet)

Kind Regards,

Gerrit Kuilder

**Comment by GerritKuilder** [comment]
So the script dif.py is installed but somehow not added to the path, my problem I think I can sort that out, later.

**Comment by elisemercury** [comment]
Hi @GerritKuilder,

Thanks a lot for your message. I just tested it myself and the CLI implementation works fine from my end.

Did you run the command in the folder where dif.py is located? If you did not add difPy to your path variables, you need to first locate into the folder where the dif.py script is installed and then you will be able to run the CLI command successfully.

For instance: if you installed difPy via the pip installer, then you would need to locate where your Python packages are installed. For me that is C:\Users\User\AppData\Local\Programs\Python\Python37\Lib\site-packages\difPy.
If you cloned difPy directly from GitHub, then locate the dif.py script it in the folder where you cloned it.

Hope this helps!

All the best,
Elise

**Comment by GerritKuilder** [comment]
Hello Elise,

Thank you, i figured out that the dif.py was indeed not i my path.
But I managed to create a custom script, bases on your example and dump the json result into a file,

I was able to replace a very time consuming javascript (days) with an under a minute python script and process the result in my node app..

Thank you for this.

Next step: take a python course....

Kind Regards,

Gerit Kuilder
