### ISSUE TITLE
Local variable 'imgs_matrix' referenced before assignment

### ISSUE THREAD

**Issue by Tesax123** [elisemercury/Duplicate-Image-Finder#7]
Hello,  

I get this error while trying to run this simple line from your package (the import works). Some help would be very welcome.

`UnboundLocalError: local variable 'imgs_matrix' referenced before assignment`

![image](https://user-images.githubusercontent.com/48088982/145710318-c86b1c42-c9b3-4270-9a81-d7a21767b064.png)

**Comment by Tesax123** [comment]
Update: I found out what was the issue. My url referenced to a directory that contained directories with images. So images were one level deeper. I still think a proper error message could have been supplied.  
Or support for searching multiple levels deep inside a directory.

**Comment by elisemercury** [comment]
Hello Tesax123,
This issue has been addressed in the new version v2.0 of the difPy.
Thanks a lot for your input!
