### ISSUE TITLE
query about json

### ISSUE THREAD

**Issue by simonmcnair** [elisemercury/Duplicate-Image-Finder#73]
Hi,
I'm trying to use the json output from search as a variable and using ```data = json.loads(str(search.result))``` but it's failing ```error Expecting property name enclosed in double quotes: line 1 column 2 (char 1)``` .  I just wondered if you can only use json with file output, and if so, why ?

Cheers
Simon

**Comment by simonmcnair** [comment]
I tried this too:
```    for key, value in vars(search).items():
        print(key, ":", value)
        if key == 'result':
             data = json.loads(str(value))```

sorry if it's wrong.  I'm a newb.

**Comment by elisemercury** [comment]
Hi @simonmcnair,

The `json.loads()` method can be used to parse a valid JSON string and convert it into a Python Dictionary. Nonetheless, `search.result` already comes in a Python dict format, hence this function doesn't work here. See [here](https://www.geeksforgeeks.org/json-loads-in-python/).

Thanks and best,
Elise
