### ISSUE TITLE
Bug: File extension filter erroneously flags files that have more than dot (.) character in file name.

### ISSUE THREAD

**Issue by MarcG2** [elisemercury/Duplicate-Image-Finder#77]
I'm running difPy via CLI and when I looked at the stats JSON file, I noticed it was flagging a bunch valid files.  Specifically it says
"ImageFilterWarning: invalid image extension."

An example file name that gets flagged is
img test 10.5 sample 5.png

I'm guessing the extension filter doesn't account for files that have dot (.) characters in the middle of the file name.

**Comment by elisemercury** [comment]
Hi @MarcG2 ,

Thanks for flagging this! Indeed, assumes that there are no dots present in the filename, hence they are marked as invalid. This will be fixed in the next DiPy update!

Thanks again and best,
Elise

**Comment by elisemercury** [comment]
Hi @MarcG2,

This issue has been fixed with [difPy v4.0.1](https://github.com/elisemercury/Duplicate-Image-Finder/releases/tag/v4.0.1). Thanks again for flagging this!

Best,
Elise
