### ISSUE TITLE
search.delete() always fails (even with matches); nested search.lower_quality dictionary 

### ISSUE THREAD

**Issue by ScrambledRK** [elisemercury/Duplicate-Image-Finder#78]
Hello!

I noticed that delete always fails even though `stats` and `result` show matching files. 
This is because the `lower_quality` dictionary ends up nested somehow. 

The workaround is to correct that nesting before calling delete.

```python
dif = difPy.build(some_directory)
search = difPy.search(dif)

search.lower_quality = search.lower_quality["lower_quality"]  # the workaround

search.delete(silent_del=True)
```

I hope to find the time to contribute a fix, but maybe its a trivial fix for some of you?
Anyway, thanks for this well written and awesome library!

**Comment by elisemercury** [comment]
Hi @ScrambledRK,

This issue has been fixed with [difPy v4.0.1](https://github.com/elisemercury/Duplicate-Image-Finder/releases/tag/v4.0.1). Thanks again for flagging this!

Best,
Elise
