### ISSUE TITLE
Incorrect results and a few further observations

### ISSUE THREAD

**Issue by audiomuze** [elisemercury/Duplicate-Image-Finder#79]
@elisemercury , I've just pulled and tested your  latest commit and have encountered what I assume are bugs:

running ```python /home/x/git/Duplicate-Image-Finder/difPy/dif.py --directory /mnt/sdc/2tag/ --output_directory /tmp --recursive True --limit_extensions True --show_progress True```:

- In one instance a 3000x3000 file was marked as lower quality than a much smaller image with otherwise same properties
![image](https://github.com/elisemercury/Duplicate-Image-Finder/assets/6852511/be03f9b4-2981-46a9-a45e-db166852be7f)

Edited extract from /tmp/difPy_20230927222221_lower_quality.json:
```
{"lower_quality": ["/pathtofile/xfolder.jpg"]}
```

- if there are x identical (i.e. their md5sum is identical) files of lower quality in the same folder and one of superior quality, difpy only flags one of the lower quality files rather than all of them

- as an observation: perusal of stats.json shows many instances of ```"ImageFilterWarning: invalid image extension."``` signifying to me that these non-image files are still being assessed rather than behaving according to the ```--limit_extensions True``` switch shown above.  Thus it looks like there's a further opportunity to enhance performance by ignoring non-image extensions.

**Comment by audiomuze** [comment]
I've just run it against another group of files and on this occasion difpy reported no lower quality images whereas in reality there were many instances of a smaller image and a larger, higher resolution image.

Perhaps the easiest way to illustrate would be for me to send you the image files to run against and compare results locally?

**Comment by audiomuze** [comment]
@elisemercury,just flagging in case you missed this?

**Comment by elisemercury** [comment]
Hi @audiomuze 

Thanks so much for flagging these issues! They will be investigated and considered with the next difPy release. 

Thanks again! 
Best
Elise

**Comment by elisemercury** [comment]
Hi @audiomuze,

[difPy v4.1.0](https://github.com/elisemercury/Duplicate-Image-Finder/releases) has been release and I would recommend testing it on your dataset to see if you can see some improvements. The new version comes with an improved comparison algorithm.

Feel free to reach out if the issue should still persist.

Thanks,
Elise
