### ISSUE TITLE
Feature: Detection of cropped duplicates

### ISSUE THREAD

**Issue by Pankovea** [elisemercury/Duplicate-Image-Finder#82]
Now the module does not recognize duplicate images that are cropped. He considers them different pictures.

**Comment by Pankovea** [comment]
I create the pull request for this feature

**Comment by CameronSima** [comment]
Been playing with this a bit, seems it can only really distingush exactly identical images. Any variations it doesn't work

**Comment by elisemercury** [comment]
Hi @Pankovea 

difPy currently only supports search for full duplicate images, not whether an image is contained within another.

This feature will likely not be implemented in difPy in the near future, though thank you for suggesting your idea! We'll keep it in mind.

Best,
Elise
