### ISSUE TITLE
Widely varied search times

### ISSUE THREAD

**Issue by CameronSima** [elisemercury/Duplicate-Image-Finder#91]
I have 2 folders each containing about 3k images, all of the same size (50x50px). One folder takes about 2-3 seconds to search, while the other takes ~20 seconds. The first returns about 15 matches, while the second returns about 30. 

Would the result size explain the widely different search time?

**Comment by elisemercury** [comment]
Hi @CameronSima, 

I'm not sure what the exact reason is for these differences, as I would need more details around the dataset used. Nonetheless, I would recommend to try the new release of [difPy v4.1.0](https://github.com/elisemercury/Duplicate-Image-Finder/releases) which comes with some improvements to the comparison algorithm. 

Thanks,
Elise
