### ISSUE TITLE
is it not possible to leverage difPy to match just a single image to a folder of images?

### ISSUE THREAD

**Issue by vesper8** [elisemercury/Duplicate-Image-Finder#92]
This was asked 2+ years ago in https://github.com/elisemercury/Duplicate-Image-Finder/issues/6

And it doesn't look like this feature has been added since.. at least if it is then it's not documented.. or maybe I'm just blind.

There are many other libraries that attempt this but I haven't found one that works very well especially when the source image is partially occluded. With the recent awesome performance improvements, I just think it would be cool to add this one feature to allow for matching one-to-many. I'd love to give that a whirl.

Thanks!

**Comment by elisemercury** [comment]
Hi @vesper8,

Thanks for your request! This feature will be evaluated for the next difPy release.

Best,
Elise
