### ISSUE TITLE
BUG:  Filepaths with square brackets, [ ], are ignored/errored

### ISSUE THREAD

**Issue by MarcG2** [elisemercury/Duplicate-Image-Finder#94]
I discovered another odd bug.  If I have files located in a folder that contains square brackets in the name, difPy ends up ignoring those files.  If the file name contains brackets, there doesn't seem to be a problem.  

I'm using the CLI version on Windows in case that makes a difference. 

EDIT:
This is in regards v4.0.1.  I haven't tried 4.1 which I noticed just came out.

**Comment by elisemercury** [comment]
Hi @MarcG2,

Thanks for reaching out! Please try the new version [difPy v4.1.0](https://github.com/elisemercury/Duplicate-Image-Finder/releases) as it comes with some improvements around the algorithm.
Feel free to reach out if the issue still persists.

Best,
Elise

**Comment by MarcG2** [comment]
I tested out the new version.  The bug is still there.   An example file path that gives that's a problem is 

D:\Pictures\[2024] Images\img1.png

If there's only one bracket as shown here, difpy works like normal

D:\Pictures\[2024 Images\img1.png

So it appears to be a parsing issue.  To replicate, simply create a folder with a bracket pair in its name and add 2 copies of the same image.

**Comment by MarcG2** [comment]
I believe I know what's causing this problem.  It's because difPy uses the glob library.   Which employs unix style file path matching.   

I recently encountered another app that failed on paths with square brackets for this exact reason.  I haven't tested it yet, but square brackets need to be escaped.  

If you don't want to implement a fix, I highly encourage you to at least update the documentation regarding this.  Almost no Windows user are going to familiar with unix style pattern matching.

**Comment by elisemercury** [comment]
Hi @MarcG2,

I was finally able to reproduce your issue. The issue would happen when a folder would have a bracket in the file path, and `in_folder` would be set to `True`. Thanks again for noticing and opening the issue.

The issue has now been fixed with version [`4.1.2`](https://github.com/elisemercury/Duplicate-Image-Finder/releases/tag/v4.1.2). Let me know if this fixes the issue on your side too.

Thanks again,
Elise
